services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coagronet_frontend_e2e
    ports:
      - "3000:3000"
    environment:
      VITE_BACKEND_URI: "https://dev.api.inmero.co/coagronet"
    restart: "no"
