# CORS
app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      - "http://inmero.co"
      - "http://www.inmero.co"
      - "https://inmero.co"
      - "https://www.inmero.co"
      - "http://dev.inmero.co"
      - "http://www.dev.inmero.co"
      - "https://dev.inmero.com"
      - "https://www.dev.inmero.co"
