spring.config.import=optional:file:.env[.properties]

# Nombre de la aplicacion
spring.application.name=Coagronet

# Configuracion del servidor
server.address=0.0.0.0
server.port=8080
server.forward-headers-strategy=framework

# Configuracion de la base de datos
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion JPA e Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.search_path=iot,public
spring.jpa.open-in-view=false

# ---------------------------------------------------------
# OPTIMIZACIONES DE PERSISTENCIA (Batching)
# ---------------------------------------------------------
# Habilita el empaquetado de sentencias SQL (Batching)
spring.jpa.properties.hibernate.jdbc.batch_size=50

# Ordena las inserciones y actualizaciones para optimizar el caché de sentencias preparadas
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Reescribe las inserciones en lote en una sola sentencia real (Específico para PostgreSQL)
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true

# Evita que Spring Data inicialice proxies de consulta antes de tener un Request activo
spring.data.jpa.repositories.bootstrap-mode=deferred

# Desactiva la validación estricta de HQL en el arranque
spring.jpa.properties.hibernate.query.startup_check=false

# Mensajes
spring.messages.basename=messages
spring.messages.encoding=UTF-8
server.error.include-message=never
server.error.include-binding-errors=never

# JWT / Seguridad
jwt.secret=${JWT_SECRET}
jwt.default-role=${JWT_DEFAULT_ROLE}

# Configuracion del correo
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URLs personalizadas de la aplicacion
app.verification-url=${URL_VERIFICATION}
app.reset-password-url=${URL_RESET_PASSWORD}

# REPORTES
path.logos=${PATH_LOGOS}
path.logo.empresa=${PATH_LOGO_COMPANY}

# Desactiva la conversión automática de tipos simples
spring.jackson.mapper.allow-coercion-of-scalars=false